on:
  push:
    branches:
      - main

name: deploy
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: toieba-vote
  IMAGE_NAME: toieba-vote_web

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0.4.0'
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: github-actions@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Build Docker image
        run: docker-compose -f docker-compose.yml -f docker-compose.prd.yml build

      - name: Tagging
        run: |-
          docker image list
          docker tag $IMAGE_NAME:latest asia.gcr.io/$PROJECT_ID/$IMAGE_NAME:${{ github.sha }}

      - name: Authorize Docker push
        run: gcloud auth configure-docker

      - name: Push Docker Image
        run: docker push asia.gcr.io/$PROJECT_ID/$IMAGE_NAME:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |-
          gcloud run deploy $SERVICE_NAME \
            --project=$PROJECT_ID \
            --image=asia.gcr.io/$PROJECT_ID/$IMAGE_NAME:${{ github.sha }} \
            --region=$REGION \
            --region="asia-northeast1" \
            --service-account=github-actions@$PROJECT_ID.iam.gserviceaccount.com \
            --allow-unauthenticated \
            --set-secrets FIREBASE_ADMIN_KEY=json-service-account-key-toieba-api:latest
